language: go
go:
  - '1.11'
script:
  - GOOS=linux go build -o main
  - zip deployment.zip main
deploy:
  provider: releases
  api_key:
    secure: MbYqhCSph95FPQal5D6CVQQAh8fMAETck2mSUb8XGXjzjMyElE3vLso9Gjf3ZLetOLOB1/rxyB65NQM3nsikk9ceSxe9wq7CCg7+BnJq4zA6+yPO9n9zax7EfQtB2dn0/2Q0Xkg7Cm+G5XZqnoZpuOtidMHB/mD/7mNLI1rSxi6k2+DPfx5IhBAulLOT7V2VfJoau0vnnE26eHCLc9y/C5UOgx+ejS8opoFstRju/mbfuaJM/vpyxUooSWwDbgV5c12LulRlTzYa0KtDxYkxVhGQ2ES1/vfyxZe5hNpmXpyQ+LCTJcwRl2T12JAt6WcSBQXReuqFM4IsC0AeFPvhTk1BYMt/nHTC+gr0Btyj6Ejx37Gui2Lxo0sLz4Ofr0jLfL4gwVDGLg0hfrO/ThJv1jddDiKOW3F/xihhWnsC++qt9QJjm0RkGD4zP5Pa6gELwQUEGbmRF3UzEfbxBIvkZfujin3BWRmzT4/O8PsqP1nrS6vPW7RfETi/iN5anG+emljVfu2AhT618sz80rz/p/9XXeX6Zl6EpcIUB0ajSr9leEpppMZe2Et+Rn7OmTEkMarRHbhs+ea4vMD0QChjGl+J96+JhwkHdxV1lHNU2il3HlIyQft1wb37yrp5HNtGJRxYTW9KYOZL+Uzz2gY2P2tQ2VXY+qzTXy9mk3Nne4Q=
  file: 'deployment.zip'
  skip_cleanup: true
  on:
    repo: asishrs/smartthings-ringalarmv2
